### ISSUE TITLE
Warning during startup, "device_state_attributes"

### ISSUE THREAD

**Issue by UniKyrn** [LaggAt/hacs-govee#59]
2022-02-07 14:17:04 WARNING (MainThread) [custom_components.govee] API is back online.
2022-02-07 14:17:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity light.kitchen_cabinet_2 (<class 'custom_components.govee.light.GoveeLightEntity'>) implements device_state_attributes. Please report it to the custom component author.

It asked that it be reported, so here you go. :)

**Comment by Nemesis24** [comment]
This is the same for me !!

**Comment by Florian-Schmidt** [comment]
Renaming inside light.py solves this as workaround..

https://community.home-assistant.io/t/warning-that-custom-component-is-using-device-state-attributes/376020

@UniKyrn Please add "device_state_attributes" to headline.

**Comment by UniKyrn** [comment]
>     @property
>     def device_state_attributes(self):
>         """Return the device state attributes."""
>         return {


At line 307 in /config/custom_components/govee/light.py

**Comment by jd1** [comment]
This is already fixed in #53.

**Comment by BeastleeUK** [comment]
> This is already fixed in #53.

Mine is still throwing this error and is at 0.2.1 from HACS: 

`2022-04-01 21:35:26 WARNING (MainThread) [custom_components.govee] API is back online.
2022-04-01 21:35:26 WARNING (MainThread) [homeassistant.helpers.entity] Entity light.desk_light (<class 'custom_components.govee.light.GoveeLightEntity'>) implements device_state_attributes. Please report it to the custom component author.`

I checked and the HACS repo version has the old code in it.  I removed my local install and re-added from HACS, this reverted the code.  I've manually fixed it for now, please can you look at getting HACS to recognise the new code?

**Comment by LaggAt** [comment]
think I never published the version. I'm closing here and will publish later.
